
const url = ``
export const productos = [

    {
        id: 1,
        img: `https://i.postimg.cc/bvqn7hrP/tilted-1-4-scaled.webp`,
        img2: `https://i.postimg.cc/XJpkPb1J/side-11-300x300.webp`,
        img3: `https://i.postimg.cc/ZKrF2jHr/front-13-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE POTENZA RE050 A",
        categoria: "AUTOMOVILES",
        rodado: `16`,
        ancho: `205`,
        radial: `30`,
    },
    {
        id: 2,
        img: `https://i.postimg.cc/kg2MDYHS/2-1.png`,
        img2: `https://i.postimg.cc/TYwfHHfs/side-300x300.webp`,
        img3: `https://i.postimg.cc/L5yR8jBv/front-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE ALENZA 001",
        categoria: "CAMIONETAS",
        rodado: `17`,
        ancho: `245`,
        radial: `60`,
    },

    {
        id: 3,
        img: `https://i.postimg.cc/bvqn7hrP/tilted-1-4-scaled.webp`,
        img2: `https://i.postimg.cc/XJpkPb1J/side-11-300x300.webp`,
        img3: `https://i.postimg.cc/ZKrF2jHr/front-13-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE POTENZA RE050 A",
        categoria: "AUTOMOVILES",
        rodado: `17`,
        ancho: `210`,
        radial: `45`,
    },
    {
        id: 4,
        img: `https://i.postimg.cc/kg2MDYHS/2-1.png`,
        img2: `https://i.postimg.cc/TYwfHHfs/side-300x300.webp`,
        img3: `https://i.postimg.cc/L5yR8jBv/front-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE ALENZA 001",
        categoria: "CAMIONETAS",
        rodado: `17`,
        ancho: `220`,
        radial: `50`,
    },

    {
        id: 1,
        img: `https://i.postimg.cc/bvqn7hrP/tilted-1-4-scaled.webp`,
        img2: `https://i.postimg.cc/XJpkPb1J/side-11-300x300.webp`,
        img3: `https://i.postimg.cc/ZKrF2jHr/front-13-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE POTENZA RE050 A",
        categoria: "AUTOMOVILES",
        rodado: `16`,
        ancho: `205`,
        radial: `30`,
    },
    {
        id: 2,
        img: `https://i.postimg.cc/kg2MDYHS/2-1.png`,
        img2: `https://i.postimg.cc/TYwfHHfs/side-300x300.webp`,
        img3: `https://i.postimg.cc/L5yR8jBv/front-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE ALENZA 001",
        categoria: "CAMIONETAS",
        rodado: `17`,
        ancho: `245`,
        radial: `60`,
    },

    {
        id: 3,
        img: `https://i.postimg.cc/bvqn7hrP/tilted-1-4-scaled.webp`,
        img2: `https://i.postimg.cc/XJpkPb1J/side-11-300x300.webp`,
        img3: `https://i.postimg.cc/ZKrF2jHr/front-13-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE POTENZA RE050 A",
        categoria: "AUTOMOVILES",
        rodado: `17`,
        ancho: `210`,
        radial: `45`,
    },
    {
        id: 4,
        img: `https://i.postimg.cc/kg2MDYHS/2-1.png`,
        img2: `https://i.postimg.cc/TYwfHHfs/side-300x300.webp`,
        img3: `https://i.postimg.cc/L5yR8jBv/front-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE ALENZA 001",
        categoria: "CAMIONETAS",
        rodado: `17`,
        ancho: `220`,
        radial: `50`,
    },
    {
        id: 1,
        img: `https://i.postimg.cc/bvqn7hrP/tilted-1-4-scaled.webp`,
        img2: `https://i.postimg.cc/XJpkPb1J/side-11-300x300.webp`,
        img3: `https://i.postimg.cc/ZKrF2jHr/front-13-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE POTENZA RE050 A",
        categoria: "AUTOMOVILES",
        rodado: `16`,
        ancho: `205`,
        radial: `30`,
    },
    {
        id: 2,
        img: `https://i.postimg.cc/kg2MDYHS/2-1.png`,
        img2: `https://i.postimg.cc/TYwfHHfs/side-300x300.webp`,
        img3: `https://i.postimg.cc/L5yR8jBv/front-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE ALENZA 001",
        categoria: "CAMIONETAS",
        rodado: `17`,
        ancho: `245`,
        radial: `60`,
    },

    {
        id: 3,
        img: `https://i.postimg.cc/bvqn7hrP/tilted-1-4-scaled.webp`,
        img2: `https://i.postimg.cc/XJpkPb1J/side-11-300x300.webp`,
        img3: `https://i.postimg.cc/ZKrF2jHr/front-13-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE POTENZA RE050 A",
        categoria: "AUTOMOVILES",
        rodado: `17`,
        ancho: `210`,
        radial: `45`,
    },
    {
        id: 4,
        img: `https://i.postimg.cc/kg2MDYHS/2-1.png`,
        img2: `https://i.postimg.cc/TYwfHHfs/side-300x300.webp`,
        img3: `https://i.postimg.cc/L5yR8jBv/front-300x300.webp`,
        img4: ``,
        titulo: "NEUMÁTICO BRIDGESTONE ALENZA 001",
        categoria: "CAMIONETAS",
        rodado: `17`,
        ancho: `220`,
        radial: `50`,
    },

    // {
    //     id: 1,
    //     img: ``,
    //     img2: ``,
    //     img3: ``,
    //     img4: ``,
    //     titulo: "",
    //     categoria: "",
    //     descripcion: ``,
    //     empresa: '',
    //     estado: 'DISPONIBLE',
    //     marca: '',
    //     modelo: '',
    //     año: '',
    //     KM: '',
    //     usado_Certificado: '',
    // },



];

